---
# tasks file for cisco_vg_acl

- name: Set SNMP Read ACL
  cisco.ios.ios_acls:
    config:
    - afi: ipv4
      acls:
      - name: 10
        acl_type: standard
        aces:
        - grant: permit
          source:
            address: 128.205.1.0
            wildcard_bits: 0.0.0.255
          sequence: 10
        - grant: permit
          source:
            address: 128.205.3.0
            wildcard_bits: 0.0.0.255
          sequence: 20
        - grant: permit
          source:
            address: 128.205.10.0
            wildcard_bits: 0.0.0.255
          sequence: 30
        - grant: permit
          source:
            address: 128.205.164.0
            wildcard_bits: 0.0.0.31
          sequence: 40
        - grant: permit
          source:
            address: 128.205.250.0
            wildcard_bits: 0.0.0.255
          sequence: 50
    state: replaced
  register: std_acl_10

- name: Update SNMP R/O ACL Remark
  cisco.ios.ios_config:
    lines:
    - remark -- SNMP Read Access --
    parents: ip access-list standard 10
    # As it applies it to the bottom of the ACL in the configuration, so you'll end up with two if you don't remove one.
    before: 
    - ip access-list standard 10
    - no remark -- SNMP Read Access --
    match: line

- name: Set Virtual Terminal ACL
  cisco.ios.ios_acls:
    config:
    - afi: ipv4
      acls:
      - name: 11
        acl_type: standard
        aces:
        - grant: permit
          source:
            address: 128.205.1.0
            wildcard_bits: 0.0.0.255
          sequence: 10
        - grant: permit
          source:
            address: 128.205.3.0
            wildcard_bits: 0.0.0.255
          sequence: 20
        - grant: permit
          source:
            address: 128.205.10.0
            wildcard_bits: 0.0.0.255
          sequence: 30
        - grant: permit
          source:
            address: 128.205.242.0
            wildcard_bits: 0.0.0.127
          sequence: 40
        - grant: permit
          source:
            address: 128.205.250.0
            wildcard_bits: 0.0.0.255
          sequence: 50
        - grant: permit
          source:
            address: 128.205.53.0
            wildcard_bits: 0.0.0.127
          sequence: 60
        - grant: permit
          source:
            address: 128.205.164.0
            wildcard_bits: 0.0.0.31
          sequence: 70
    state: replaced
  register: std_acl_11

- name: Update VTY ACL Remark
  cisco.ios.ios_config:
    lines:
    - remark -- SNMP Write and Telnet Access --
    parents: ip access-list standard 11
    # As it applies it to the bottom of the ACL in the configuration, so you'll end up with two if you don't remove one.
    before: 
    - ip access-list standard 11
    - no remark -- SNMP Write and Telnet Access --
    match: line

- name: Set Management VLAN ACL
  cisco.ios.ios_acls:
    config:
    - afi: ipv4
      acls:
      - name: 12
        acl_type: standard
        aces:
        - grant: permit
          source:
            address: 10.1.0.0
            wildcard_bits: 0.0.255.255
          sequence: 10
        - grant: permit
          source:
            address: 128.205.1.0
            wildcard_bits: 0.0.0.255
          sequence: 20
        - grant: permit
          source:
            address: 128.205.3.0
            wildcard_bits: 0.0.0.255
          sequence: 30
        - grant: permit
          source:
            address: 128.205.10.0
            wildcard_bits: 0.0.0.255
          sequence: 40
        - grant: permit
          source:
            address: 128.205.53.0
            wildcard_bits: 0.0.0.127
          sequence: 50
        - grant: permit
          source:
            address: 128.205.106.0
            wildcard_bits: 0.0.0.255
          sequence: 60
        - grant: permit
          source:
            address: 128.205.200.0
            wildcard_bits: 0.0.0.255
          sequence: 70
        - grant: permit
          source:
            address: 128.205.242.0
            wildcard_bits: 0.0.0.127
          sequence: 80
        - grant: permit
          source:
            address: 128.205.250.0
            wildcard_bits: 0.0.0.255
          sequence: 90
        - grant: permit
          source:
            address: 128.205.164.0
            wildcard_bits: 0.0.0.31
          sequence: 100
    state: replaced
  register: std_acl_12

- name: Update Management VLAN ACL Remark
  cisco.ios.ios_config:
    lines:
    - remark -- VLAN1 mgmt, radius, ntp access --
    parents: ip access-list standard 12
    # As it applies it to the bottom of the ACL in the configuration, so you'll end up with two if you don't remove one.
    before:
    - ip access-list standard 12
    - no remark -- VLAN1 mgmt, radius, ntp access --
    match: line

- name: Set NTP ACL
  cisco.ios.ios_acls:
    config:
    - afi: ipv4
      acls:
      - name: 99
        acl_type: standard
        aces:
        - grant: permit
          source:
            address: 128.205.1.69
          sequence: 10
        - grant: permit
          source:
            address: 128.205.1.70
          sequence: 20
        - grant: permit
          source:
            address: 128.205.1.71
          sequence: 30
    state: replaced
  register: std_acl_99

- name: Update NTP ACL Remark
  cisco.ios.ios_config:
    lines:
    - remark -- NTP Peer Access --
    parents: ip access-list standard 99
    # As it applies it to the bottom of the ACL in the configuration, so you'll end up with two if you don't remove one.
    before: 
    - ip access-list standard 99 
    - no remark -- NTP Peer Access --
    - no remark ntp
    match: line

- name: Save configuration if changed
  cisco.ios.ios_config:
    save_when: modified
