---
- hosts: ALL_VG
  gather_facts: no
  vars:
    dns_servers:
      - ip name-server 128.205.1.100
      - ip name-server 128.205.1.101
      - ip name-server 128.205.1.102

  tasks:
  - name: get current DNS servers
    cisco.ios.ios_command:
      commands:
        - "show running-config full | include ip name-server"
    register: get_config

  - name: set DNS servers
    with_items: "{{ dns_servers }}"
    cisco.ios.ios_config:
      lines:
        - "{{ item }}"
    register: set_dns

  - name: remove extra DNS servers
    when: "(get_config.stdout_lines[0] != '') and (item not in dns_servers)"
    with_items: "{{ get_config.stdout_lines[0] }}"
    register: bad_dns
    cisco.ios.ios_config:
      lines:
        - "no {{ item }}"

  - name: save the running config if modified
    cisco.ios.ios_config:
      save_when: modified
